# coding: utf-8

# flake8: noqa
"""
Telegram Bot API - REST API Client
Auto-generated OpenAPI schema

## Metadata

- **Copyright**: Copyright (c) 2025 Qntx
- **Author**: ΣX <gitctrlx@gmail.com>
- **Version**: 9.0.0
- **Modified**: 2025-07-01T14:15:10.340422036Z[Etc/UTC]
- **Generator Version**: 7.14.0

<details>
<summary><strong>⚠️ Important Disclaimer & Limitation of Liability</strong></summary>
<br>
> **IMPORTANT**: This software is provided "as is" without any warranties, express or implied, including but not limited
> to warranties of merchantability, fitness for a particular purpose, or non-infringement. The developers, contributors,
> and licensors (collectively, "Developers") make no representations regarding the accuracy, completeness, or reliability
> of this software or its outputs.
>
> This client is not intended to provide financial, investment, tax, or legal advice. It facilitates interaction with the
> Telegram Bot API service but does not endorse or recommend any financial actions, including the purchase, sale, or holding of
> financial instruments (e.g., stocks, bonds, derivatives, cryptocurrencies). Users must consult qualified financial or
> legal professionals before making decisions based on this software's outputs.
>
> Financial markets are inherently speculative and carry significant risks. Using this software in trading, analysis, or
> other financial activities may result in substantial losses, including total loss of capital. The Developers are not
> liable for any losses or damages arising from such use. Users assume full responsibility for validating the software's
> outputs and ensuring their suitability for intended purposes.
>
> This client may rely on third-party data or services (e.g., market feeds, APIs). The Developers do not control or verify
> the accuracy of these services and are not liable for any errors, delays, or losses resulting from their use. Users must
> comply with third-party terms and conditions.
>
> Users are solely responsible for ensuring compliance with all applicable financial, tax, and regulatory requirements in
> their jurisdiction. This includes obtaining necessary licenses or approvals for trading or investment activities. The
> Developers disclaim liability for any legal consequences arising from non-compliance.
>
> To the fullest extent permitted by law, the Developers shall not be liable for any direct, indirect, incidental,
> consequential, or punitive damages arising from the use or inability to use this software, including but not limited to
> loss of profits, data, or business opportunities.

</details>
"""  # noqa: E501


# import models into model package
from tele_rest.models.accepted_gift_types import AcceptedGiftTypes
from tele_rest.models.affiliate_info import AffiliateInfo
from tele_rest.models.animation import Animation
from tele_rest.models.answer_callback_query_post_request import AnswerCallbackQueryPostRequest
from tele_rest.models.answer_inline_query_post_request import AnswerInlineQueryPostRequest
from tele_rest.models.answer_pre_checkout_query_post_request import AnswerPreCheckoutQueryPostRequest
from tele_rest.models.answer_shipping_query_post_request import AnswerShippingQueryPostRequest
from tele_rest.models.answer_web_app_query_post200_response import AnswerWebAppQueryPost200Response
from tele_rest.models.answer_web_app_query_post_request import AnswerWebAppQueryPostRequest
from tele_rest.models.approve_chat_join_request_post_request import ApproveChatJoinRequestPostRequest
from tele_rest.models.audio import Audio
from tele_rest.models.background_fill import BackgroundFill
from tele_rest.models.background_fill_freeform_gradient import BackgroundFillFreeformGradient
from tele_rest.models.background_fill_gradient import BackgroundFillGradient
from tele_rest.models.background_fill_solid import BackgroundFillSolid
from tele_rest.models.background_type import BackgroundType
from tele_rest.models.background_type_chat_theme import BackgroundTypeChatTheme
from tele_rest.models.background_type_fill import BackgroundTypeFill
from tele_rest.models.background_type_pattern import BackgroundTypePattern
from tele_rest.models.background_type_wallpaper import BackgroundTypeWallpaper
from tele_rest.models.ban_chat_member_post_request import BanChatMemberPostRequest
from tele_rest.models.ban_chat_member_post_request_chat_id import BanChatMemberPostRequestChatId
from tele_rest.models.ban_chat_sender_chat_post_request import BanChatSenderChatPostRequest
from tele_rest.models.birthdate import Birthdate
from tele_rest.models.bot_command import BotCommand
from tele_rest.models.bot_command_scope import BotCommandScope
from tele_rest.models.bot_command_scope_all_chat_administrators import BotCommandScopeAllChatAdministrators
from tele_rest.models.bot_command_scope_all_group_chats import BotCommandScopeAllGroupChats
from tele_rest.models.bot_command_scope_all_private_chats import BotCommandScopeAllPrivateChats
from tele_rest.models.bot_command_scope_chat import BotCommandScopeChat
from tele_rest.models.bot_command_scope_chat_administrators import BotCommandScopeChatAdministrators
from tele_rest.models.bot_command_scope_chat_member import BotCommandScopeChatMember
from tele_rest.models.bot_command_scope_default import BotCommandScopeDefault
from tele_rest.models.bot_description import BotDescription
from tele_rest.models.bot_name import BotName
from tele_rest.models.bot_short_description import BotShortDescription
from tele_rest.models.business_bot_rights import BusinessBotRights
from tele_rest.models.business_connection import BusinessConnection
from tele_rest.models.business_intro import BusinessIntro
from tele_rest.models.business_location import BusinessLocation
from tele_rest.models.business_messages_deleted import BusinessMessagesDeleted
from tele_rest.models.business_opening_hours import BusinessOpeningHours
from tele_rest.models.business_opening_hours_interval import BusinessOpeningHoursInterval
from tele_rest.models.callback_query import CallbackQuery
from tele_rest.models.chat import Chat
from tele_rest.models.chat_administrator_rights import ChatAdministratorRights
from tele_rest.models.chat_background import ChatBackground
from tele_rest.models.chat_boost import ChatBoost
from tele_rest.models.chat_boost_added import ChatBoostAdded
from tele_rest.models.chat_boost_removed import ChatBoostRemoved
from tele_rest.models.chat_boost_source import ChatBoostSource
from tele_rest.models.chat_boost_source_gift_code import ChatBoostSourceGiftCode
from tele_rest.models.chat_boost_source_giveaway import ChatBoostSourceGiveaway
from tele_rest.models.chat_boost_source_premium import ChatBoostSourcePremium
from tele_rest.models.chat_boost_updated import ChatBoostUpdated
from tele_rest.models.chat_full_info import ChatFullInfo
from tele_rest.models.chat_invite_link import ChatInviteLink
from tele_rest.models.chat_join_request import ChatJoinRequest
from tele_rest.models.chat_location import ChatLocation
from tele_rest.models.chat_member import ChatMember
from tele_rest.models.chat_member_administrator import ChatMemberAdministrator
from tele_rest.models.chat_member_banned import ChatMemberBanned
from tele_rest.models.chat_member_left import ChatMemberLeft
from tele_rest.models.chat_member_member import ChatMemberMember
from tele_rest.models.chat_member_owner import ChatMemberOwner
from tele_rest.models.chat_member_restricted import ChatMemberRestricted
from tele_rest.models.chat_member_updated import ChatMemberUpdated
from tele_rest.models.chat_permissions import ChatPermissions
from tele_rest.models.chat_photo import ChatPhoto
from tele_rest.models.chat_shared import ChatShared
from tele_rest.models.chosen_inline_result import ChosenInlineResult
from tele_rest.models.close_forum_topic_post_request import CloseForumTopicPostRequest
from tele_rest.models.contact import Contact
from tele_rest.models.convert_gift_to_stars_post_request import ConvertGiftToStarsPostRequest
from tele_rest.models.copy_message_post200_response import CopyMessagePost200Response
from tele_rest.models.copy_message_post_request import CopyMessagePostRequest
from tele_rest.models.copy_messages_post_request import CopyMessagesPostRequest
from tele_rest.models.copy_text_button import CopyTextButton
from tele_rest.models.create_chat_invite_link_post200_response import CreateChatInviteLinkPost200Response
from tele_rest.models.create_chat_invite_link_post_request import CreateChatInviteLinkPostRequest
from tele_rest.models.create_chat_subscription_invite_link_post_request import CreateChatSubscriptionInviteLinkPostRequest
from tele_rest.models.create_chat_subscription_invite_link_post_request_chat_id import CreateChatSubscriptionInviteLinkPostRequestChatId
from tele_rest.models.create_forum_topic_post200_response import CreateForumTopicPost200Response
from tele_rest.models.create_forum_topic_post_request import CreateForumTopicPostRequest
from tele_rest.models.create_invoice_link_post_request import CreateInvoiceLinkPostRequest
from tele_rest.models.delete_business_messages_post_request import DeleteBusinessMessagesPostRequest
from tele_rest.models.delete_chat_sticker_set_post_request import DeleteChatStickerSetPostRequest
from tele_rest.models.delete_message_post_request import DeleteMessagePostRequest
from tele_rest.models.delete_messages_post_request import DeleteMessagesPostRequest
from tele_rest.models.delete_my_commands_post_request import DeleteMyCommandsPostRequest
from tele_rest.models.delete_sticker_from_set_post_request import DeleteStickerFromSetPostRequest
from tele_rest.models.delete_sticker_set_post_request import DeleteStickerSetPostRequest
from tele_rest.models.delete_story_post_request import DeleteStoryPostRequest
from tele_rest.models.delete_webhook_post_request import DeleteWebhookPostRequest
from tele_rest.models.dice import Dice
from tele_rest.models.document import Document
from tele_rest.models.edit_chat_invite_link_post_request import EditChatInviteLinkPostRequest
from tele_rest.models.edit_chat_subscription_invite_link_post_request import EditChatSubscriptionInviteLinkPostRequest
from tele_rest.models.edit_forum_topic_post_request import EditForumTopicPostRequest
from tele_rest.models.edit_general_forum_topic_post_request import EditGeneralForumTopicPostRequest
from tele_rest.models.edit_message_caption_post_request import EditMessageCaptionPostRequest
from tele_rest.models.edit_message_live_location_post_request import EditMessageLiveLocationPostRequest
from tele_rest.models.edit_message_reply_markup_post_request import EditMessageReplyMarkupPostRequest
from tele_rest.models.edit_message_text_post200_response import EditMessageTextPost200Response
from tele_rest.models.edit_message_text_post200_response_result import EditMessageTextPost200ResponseResult
from tele_rest.models.edit_message_text_post_request import EditMessageTextPostRequest
from tele_rest.models.edit_message_text_post_request_chat_id import EditMessageTextPostRequestChatId
from tele_rest.models.edit_user_star_subscription_post_request import EditUserStarSubscriptionPostRequest
from tele_rest.models.encrypted_credentials import EncryptedCredentials
from tele_rest.models.encrypted_passport_element import EncryptedPassportElement
from tele_rest.models.error import Error
from tele_rest.models.export_chat_invite_link_post200_response import ExportChatInviteLinkPost200Response
from tele_rest.models.export_chat_invite_link_post_request import ExportChatInviteLinkPostRequest
from tele_rest.models.external_reply_info import ExternalReplyInfo
from tele_rest.models.file import File
from tele_rest.models.force_reply import ForceReply
from tele_rest.models.forum_topic import ForumTopic
from tele_rest.models.forum_topic_created import ForumTopicCreated
from tele_rest.models.forum_topic_edited import ForumTopicEdited
from tele_rest.models.forward_message_post_request import ForwardMessagePostRequest
from tele_rest.models.forward_message_post_request_from_chat_id import ForwardMessagePostRequestFromChatId
from tele_rest.models.forward_messages_post200_response import ForwardMessagesPost200Response
from tele_rest.models.forward_messages_post_request import ForwardMessagesPostRequest
from tele_rest.models.forward_messages_post_request_from_chat_id import ForwardMessagesPostRequestFromChatId
from tele_rest.models.game import Game
from tele_rest.models.game_high_score import GameHighScore
from tele_rest.models.get_available_gifts_post200_response import GetAvailableGiftsPost200Response
from tele_rest.models.get_business_account_gifts_post200_response import GetBusinessAccountGiftsPost200Response
from tele_rest.models.get_business_account_gifts_post_request import GetBusinessAccountGiftsPostRequest
from tele_rest.models.get_business_account_star_balance_post200_response import GetBusinessAccountStarBalancePost200Response
from tele_rest.models.get_business_connection_post200_response import GetBusinessConnectionPost200Response
from tele_rest.models.get_business_connection_post_request import GetBusinessConnectionPostRequest
from tele_rest.models.get_chat_administrators_post200_response import GetChatAdministratorsPost200Response
from tele_rest.models.get_chat_member_count_post200_response import GetChatMemberCountPost200Response
from tele_rest.models.get_chat_member_post200_response import GetChatMemberPost200Response
from tele_rest.models.get_chat_member_post_request import GetChatMemberPostRequest
from tele_rest.models.get_chat_menu_button_post200_response import GetChatMenuButtonPost200Response
from tele_rest.models.get_chat_menu_button_post_request import GetChatMenuButtonPostRequest
from tele_rest.models.get_chat_post200_response import GetChatPost200Response
from tele_rest.models.get_custom_emoji_stickers_post_request import GetCustomEmojiStickersPostRequest
from tele_rest.models.get_file_post200_response import GetFilePost200Response
from tele_rest.models.get_file_post_request import GetFilePostRequest
from tele_rest.models.get_forum_topic_icon_stickers_post200_response import GetForumTopicIconStickersPost200Response
from tele_rest.models.get_game_high_scores_post200_response import GetGameHighScoresPost200Response
from tele_rest.models.get_game_high_scores_post_request import GetGameHighScoresPostRequest
from tele_rest.models.get_me_post200_response import GetMePost200Response
from tele_rest.models.get_my_commands_post200_response import GetMyCommandsPost200Response
from tele_rest.models.get_my_commands_post_request import GetMyCommandsPostRequest
from tele_rest.models.get_my_default_administrator_rights_post200_response import GetMyDefaultAdministratorRightsPost200Response
from tele_rest.models.get_my_default_administrator_rights_post_request import GetMyDefaultAdministratorRightsPostRequest
from tele_rest.models.get_my_description_post200_response import GetMyDescriptionPost200Response
from tele_rest.models.get_my_name_post200_response import GetMyNamePost200Response
from tele_rest.models.get_my_name_post_request import GetMyNamePostRequest
from tele_rest.models.get_my_short_description_post200_response import GetMyShortDescriptionPost200Response
from tele_rest.models.get_star_transactions_post200_response import GetStarTransactionsPost200Response
from tele_rest.models.get_star_transactions_post_request import GetStarTransactionsPostRequest
from tele_rest.models.get_sticker_set_post200_response import GetStickerSetPost200Response
from tele_rest.models.get_sticker_set_post_request import GetStickerSetPostRequest
from tele_rest.models.get_updates_post200_response import GetUpdatesPost200Response
from tele_rest.models.get_updates_post_request import GetUpdatesPostRequest
from tele_rest.models.get_user_chat_boosts_post200_response import GetUserChatBoostsPost200Response
from tele_rest.models.get_user_chat_boosts_post_request import GetUserChatBoostsPostRequest
from tele_rest.models.get_user_chat_boosts_post_request_chat_id import GetUserChatBoostsPostRequestChatId
from tele_rest.models.get_user_profile_photos_post200_response import GetUserProfilePhotosPost200Response
from tele_rest.models.get_user_profile_photos_post_request import GetUserProfilePhotosPostRequest
from tele_rest.models.get_webhook_info_post200_response import GetWebhookInfoPost200Response
from tele_rest.models.gift import Gift
from tele_rest.models.gift_info import GiftInfo
from tele_rest.models.gift_premium_subscription_post_request import GiftPremiumSubscriptionPostRequest
from tele_rest.models.gifts import Gifts
from tele_rest.models.giveaway import Giveaway
from tele_rest.models.giveaway_completed import GiveawayCompleted
from tele_rest.models.giveaway_created import GiveawayCreated
from tele_rest.models.giveaway_winners import GiveawayWinners
from tele_rest.models.inaccessible_message import InaccessibleMessage
from tele_rest.models.inline_keyboard_button import InlineKeyboardButton
from tele_rest.models.inline_keyboard_markup import InlineKeyboardMarkup
from tele_rest.models.inline_query import InlineQuery
from tele_rest.models.inline_query_result import InlineQueryResult
from tele_rest.models.inline_query_result_article import InlineQueryResultArticle
from tele_rest.models.inline_query_result_audio import InlineQueryResultAudio
from tele_rest.models.inline_query_result_cached_audio import InlineQueryResultCachedAudio
from tele_rest.models.inline_query_result_cached_document import InlineQueryResultCachedDocument
from tele_rest.models.inline_query_result_cached_gif import InlineQueryResultCachedGif
from tele_rest.models.inline_query_result_cached_mpeg4_gif import InlineQueryResultCachedMpeg4Gif
from tele_rest.models.inline_query_result_cached_photo import InlineQueryResultCachedPhoto
from tele_rest.models.inline_query_result_cached_sticker import InlineQueryResultCachedSticker
from tele_rest.models.inline_query_result_cached_video import InlineQueryResultCachedVideo
from tele_rest.models.inline_query_result_cached_voice import InlineQueryResultCachedVoice
from tele_rest.models.inline_query_result_contact import InlineQueryResultContact
from tele_rest.models.inline_query_result_document import InlineQueryResultDocument
from tele_rest.models.inline_query_result_game import InlineQueryResultGame
from tele_rest.models.inline_query_result_gif import InlineQueryResultGif
from tele_rest.models.inline_query_result_location import InlineQueryResultLocation
from tele_rest.models.inline_query_result_mpeg4_gif import InlineQueryResultMpeg4Gif
from tele_rest.models.inline_query_result_photo import InlineQueryResultPhoto
from tele_rest.models.inline_query_result_venue import InlineQueryResultVenue
from tele_rest.models.inline_query_result_video import InlineQueryResultVideo
from tele_rest.models.inline_query_result_voice import InlineQueryResultVoice
from tele_rest.models.inline_query_results_button import InlineQueryResultsButton
from tele_rest.models.input_contact_message_content import InputContactMessageContent
from tele_rest.models.input_invoice_message_content import InputInvoiceMessageContent
from tele_rest.models.input_location_message_content import InputLocationMessageContent
from tele_rest.models.input_media import InputMedia
from tele_rest.models.input_media_animation import InputMediaAnimation
from tele_rest.models.input_media_audio import InputMediaAudio
from tele_rest.models.input_media_document import InputMediaDocument
from tele_rest.models.input_media_photo import InputMediaPhoto
from tele_rest.models.input_media_video import InputMediaVideo
from tele_rest.models.input_message_content import InputMessageContent
from tele_rest.models.input_paid_media import InputPaidMedia
from tele_rest.models.input_paid_media_photo import InputPaidMediaPhoto
from tele_rest.models.input_paid_media_video import InputPaidMediaVideo
from tele_rest.models.input_poll_option import InputPollOption
from tele_rest.models.input_profile_photo import InputProfilePhoto
from tele_rest.models.input_profile_photo_animated import InputProfilePhotoAnimated
from tele_rest.models.input_profile_photo_static import InputProfilePhotoStatic
from tele_rest.models.input_sticker import InputSticker
from tele_rest.models.input_story_content import InputStoryContent
from tele_rest.models.input_story_content_photo import InputStoryContentPhoto
from tele_rest.models.input_story_content_video import InputStoryContentVideo
from tele_rest.models.input_text_message_content import InputTextMessageContent
from tele_rest.models.input_venue_message_content import InputVenueMessageContent
from tele_rest.models.invoice import Invoice
from tele_rest.models.keyboard_button import KeyboardButton
from tele_rest.models.keyboard_button_poll_type import KeyboardButtonPollType
from tele_rest.models.keyboard_button_request_chat import KeyboardButtonRequestChat
from tele_rest.models.keyboard_button_request_users import KeyboardButtonRequestUsers
from tele_rest.models.labeled_price import LabeledPrice
from tele_rest.models.leave_chat_post_request import LeaveChatPostRequest
from tele_rest.models.leave_chat_post_request_chat_id import LeaveChatPostRequestChatId
from tele_rest.models.link_preview_options import LinkPreviewOptions
from tele_rest.models.location import Location
from tele_rest.models.location_address import LocationAddress
from tele_rest.models.login_url import LoginUrl
from tele_rest.models.mask_position import MaskPosition
from tele_rest.models.maybe_inaccessible_message import MaybeInaccessibleMessage
from tele_rest.models.menu_button import MenuButton
from tele_rest.models.menu_button_commands import MenuButtonCommands
from tele_rest.models.menu_button_default import MenuButtonDefault
from tele_rest.models.menu_button_web_app import MenuButtonWebApp
from tele_rest.models.message import Message
from tele_rest.models.message_auto_delete_timer_changed import MessageAutoDeleteTimerChanged
from tele_rest.models.message_entity import MessageEntity
from tele_rest.models.message_id import MessageId
from tele_rest.models.message_origin import MessageOrigin
from tele_rest.models.message_origin_channel import MessageOriginChannel
from tele_rest.models.message_origin_chat import MessageOriginChat
from tele_rest.models.message_origin_hidden_user import MessageOriginHiddenUser
from tele_rest.models.message_origin_user import MessageOriginUser
from tele_rest.models.message_reaction_count_updated import MessageReactionCountUpdated
from tele_rest.models.message_reaction_updated import MessageReactionUpdated
from tele_rest.models.order_info import OrderInfo
from tele_rest.models.owned_gift import OwnedGift
from tele_rest.models.owned_gift_regular import OwnedGiftRegular
from tele_rest.models.owned_gift_unique import OwnedGiftUnique
from tele_rest.models.owned_gifts import OwnedGifts
from tele_rest.models.paid_media import PaidMedia
from tele_rest.models.paid_media_info import PaidMediaInfo
from tele_rest.models.paid_media_photo import PaidMediaPhoto
from tele_rest.models.paid_media_preview import PaidMediaPreview
from tele_rest.models.paid_media_purchased import PaidMediaPurchased
from tele_rest.models.paid_media_video import PaidMediaVideo
from tele_rest.models.paid_message_price_changed import PaidMessagePriceChanged
from tele_rest.models.passport_data import PassportData
from tele_rest.models.passport_element_error import PassportElementError
from tele_rest.models.passport_element_error_data_field import PassportElementErrorDataField
from tele_rest.models.passport_element_error_file import PassportElementErrorFile
from tele_rest.models.passport_element_error_files import PassportElementErrorFiles
from tele_rest.models.passport_element_error_front_side import PassportElementErrorFrontSide
from tele_rest.models.passport_element_error_reverse_side import PassportElementErrorReverseSide
from tele_rest.models.passport_element_error_selfie import PassportElementErrorSelfie
from tele_rest.models.passport_element_error_translation_file import PassportElementErrorTranslationFile
from tele_rest.models.passport_element_error_translation_files import PassportElementErrorTranslationFiles
from tele_rest.models.passport_element_error_unspecified import PassportElementErrorUnspecified
from tele_rest.models.passport_file import PassportFile
from tele_rest.models.photo_size import PhotoSize
from tele_rest.models.pin_chat_message_post_request import PinChatMessagePostRequest
from tele_rest.models.poll import Poll
from tele_rest.models.poll_answer import PollAnswer
from tele_rest.models.poll_option import PollOption
from tele_rest.models.post_story_post200_response import PostStoryPost200Response
from tele_rest.models.pre_checkout_query import PreCheckoutQuery
from tele_rest.models.prepared_inline_message import PreparedInlineMessage
from tele_rest.models.promote_chat_member_post_request import PromoteChatMemberPostRequest
from tele_rest.models.proximity_alert_triggered import ProximityAlertTriggered
from tele_rest.models.reaction_count import ReactionCount
from tele_rest.models.reaction_type import ReactionType
from tele_rest.models.reaction_type_custom_emoji import ReactionTypeCustomEmoji
from tele_rest.models.reaction_type_emoji import ReactionTypeEmoji
from tele_rest.models.reaction_type_paid import ReactionTypePaid
from tele_rest.models.read_business_message_post_request import ReadBusinessMessagePostRequest
from tele_rest.models.refund_star_payment_post_request import RefundStarPaymentPostRequest
from tele_rest.models.refunded_payment import RefundedPayment
from tele_rest.models.remove_business_account_profile_photo_post_request import RemoveBusinessAccountProfilePhotoPostRequest
from tele_rest.models.remove_user_verification_post_request import RemoveUserVerificationPostRequest
from tele_rest.models.reply_keyboard_markup import ReplyKeyboardMarkup
from tele_rest.models.reply_keyboard_remove import ReplyKeyboardRemove
from tele_rest.models.reply_parameters import ReplyParameters
from tele_rest.models.reply_parameters_chat_id import ReplyParametersChatId
from tele_rest.models.response_parameters import ResponseParameters
from tele_rest.models.restrict_chat_member_post_request import RestrictChatMemberPostRequest
from tele_rest.models.restrict_chat_member_post_request_chat_id import RestrictChatMemberPostRequestChatId
from tele_rest.models.revenue_withdrawal_state import RevenueWithdrawalState
from tele_rest.models.revenue_withdrawal_state_failed import RevenueWithdrawalStateFailed
from tele_rest.models.revenue_withdrawal_state_pending import RevenueWithdrawalStatePending
from tele_rest.models.revenue_withdrawal_state_succeeded import RevenueWithdrawalStateSucceeded
from tele_rest.models.revoke_chat_invite_link_post_request import RevokeChatInviteLinkPostRequest
from tele_rest.models.revoke_chat_invite_link_post_request_chat_id import RevokeChatInviteLinkPostRequestChatId
from tele_rest.models.save_prepared_inline_message_post200_response import SavePreparedInlineMessagePost200Response
from tele_rest.models.save_prepared_inline_message_post_request import SavePreparedInlineMessagePostRequest
from tele_rest.models.send_animation_post_request_animation import SendAnimationPostRequestAnimation
from tele_rest.models.send_audio_post_request_audio import SendAudioPostRequestAudio
from tele_rest.models.send_audio_post_request_thumbnail import SendAudioPostRequestThumbnail
from tele_rest.models.send_chat_action_post_request import SendChatActionPostRequest
from tele_rest.models.send_contact_post_request import SendContactPostRequest
from tele_rest.models.send_dice_post_request import SendDicePostRequest
from tele_rest.models.send_document_post_request_document import SendDocumentPostRequestDocument
from tele_rest.models.send_game_post_request import SendGamePostRequest
from tele_rest.models.send_gift_post_request import SendGiftPostRequest
from tele_rest.models.send_gift_post_request_chat_id import SendGiftPostRequestChatId
from tele_rest.models.send_invoice_post_request import SendInvoicePostRequest
from tele_rest.models.send_location_post_request import SendLocationPostRequest
from tele_rest.models.send_media_group_post200_response import SendMediaGroupPost200Response
from tele_rest.models.send_media_group_post_request_media_inner import SendMediaGroupPostRequestMediaInner
from tele_rest.models.send_message_post200_response import SendMessagePost200Response
from tele_rest.models.send_message_post_request import SendMessagePostRequest
from tele_rest.models.send_message_post_request_chat_id import SendMessagePostRequestChatId
from tele_rest.models.send_message_post_request_reply_markup import SendMessagePostRequestReplyMarkup
from tele_rest.models.send_paid_media_post_request_chat_id import SendPaidMediaPostRequestChatId
from tele_rest.models.send_photo_post_request_photo import SendPhotoPostRequestPhoto
from tele_rest.models.send_poll_post_request import SendPollPostRequest
from tele_rest.models.send_sticker_post_request_sticker import SendStickerPostRequestSticker
from tele_rest.models.send_venue_post_request import SendVenuePostRequest
from tele_rest.models.send_video_note_post_request_video_note import SendVideoNotePostRequestVideoNote
from tele_rest.models.send_video_post_request_cover import SendVideoPostRequestCover
from tele_rest.models.send_video_post_request_video import SendVideoPostRequestVideo
from tele_rest.models.send_voice_post_request_voice import SendVoicePostRequestVoice
from tele_rest.models.sent_web_app_message import SentWebAppMessage
from tele_rest.models.set_business_account_bio_post_request import SetBusinessAccountBioPostRequest
from tele_rest.models.set_business_account_gift_settings_post_request import SetBusinessAccountGiftSettingsPostRequest
from tele_rest.models.set_business_account_name_post_request import SetBusinessAccountNamePostRequest
from tele_rest.models.set_business_account_username_post_request import SetBusinessAccountUsernamePostRequest
from tele_rest.models.set_chat_administrator_custom_title_post_request import SetChatAdministratorCustomTitlePostRequest
from tele_rest.models.set_chat_description_post_request import SetChatDescriptionPostRequest
from tele_rest.models.set_chat_menu_button_post_request import SetChatMenuButtonPostRequest
from tele_rest.models.set_chat_permissions_post_request import SetChatPermissionsPostRequest
from tele_rest.models.set_chat_sticker_set_post_request import SetChatStickerSetPostRequest
from tele_rest.models.set_chat_title_post_request import SetChatTitlePostRequest
from tele_rest.models.set_custom_emoji_sticker_set_thumbnail_post_request import SetCustomEmojiStickerSetThumbnailPostRequest
from tele_rest.models.set_game_score_post_request import SetGameScorePostRequest
from tele_rest.models.set_message_reaction_post_request import SetMessageReactionPostRequest
from tele_rest.models.set_my_commands_post_request import SetMyCommandsPostRequest
from tele_rest.models.set_my_default_administrator_rights_post_request import SetMyDefaultAdministratorRightsPostRequest
from tele_rest.models.set_my_description_post_request import SetMyDescriptionPostRequest
from tele_rest.models.set_my_name_post_request import SetMyNamePostRequest
from tele_rest.models.set_my_short_description_post_request import SetMyShortDescriptionPostRequest
from tele_rest.models.set_passport_data_errors_post_request import SetPassportDataErrorsPostRequest
from tele_rest.models.set_sticker_emoji_list_post_request import SetStickerEmojiListPostRequest
from tele_rest.models.set_sticker_keywords_post_request import SetStickerKeywordsPostRequest
from tele_rest.models.set_sticker_mask_position_post_request import SetStickerMaskPositionPostRequest
from tele_rest.models.set_sticker_position_in_set_post_request import SetStickerPositionInSetPostRequest
from tele_rest.models.set_sticker_set_thumbnail_post_request_thumbnail import SetStickerSetThumbnailPostRequestThumbnail
from tele_rest.models.set_sticker_set_title_post_request import SetStickerSetTitlePostRequest
from tele_rest.models.set_user_emoji_status_post_request import SetUserEmojiStatusPostRequest
from tele_rest.models.set_webhook_post200_response import SetWebhookPost200Response
from tele_rest.models.shared_user import SharedUser
from tele_rest.models.shipping_address import ShippingAddress
from tele_rest.models.shipping_option import ShippingOption
from tele_rest.models.shipping_query import ShippingQuery
from tele_rest.models.star_amount import StarAmount
from tele_rest.models.star_transaction import StarTransaction
from tele_rest.models.star_transactions import StarTransactions
from tele_rest.models.sticker import Sticker
from tele_rest.models.sticker_set import StickerSet
from tele_rest.models.stop_message_live_location_post_request import StopMessageLiveLocationPostRequest
from tele_rest.models.stop_poll_post200_response import StopPollPost200Response
from tele_rest.models.stop_poll_post_request import StopPollPostRequest
from tele_rest.models.story import Story
from tele_rest.models.story_area import StoryArea
from tele_rest.models.story_area_position import StoryAreaPosition
from tele_rest.models.story_area_type import StoryAreaType
from tele_rest.models.story_area_type_link import StoryAreaTypeLink
from tele_rest.models.story_area_type_location import StoryAreaTypeLocation
from tele_rest.models.story_area_type_suggested_reaction import StoryAreaTypeSuggestedReaction
from tele_rest.models.story_area_type_unique_gift import StoryAreaTypeUniqueGift
from tele_rest.models.story_area_type_weather import StoryAreaTypeWeather
from tele_rest.models.successful_payment import SuccessfulPayment
from tele_rest.models.switch_inline_query_chosen_chat import SwitchInlineQueryChosenChat
from tele_rest.models.text_quote import TextQuote
from tele_rest.models.transaction_partner import TransactionPartner
from tele_rest.models.transaction_partner_affiliate_program import TransactionPartnerAffiliateProgram
from tele_rest.models.transaction_partner_chat import TransactionPartnerChat
from tele_rest.models.transaction_partner_fragment import TransactionPartnerFragment
from tele_rest.models.transaction_partner_other import TransactionPartnerOther
from tele_rest.models.transaction_partner_telegram_ads import TransactionPartnerTelegramAds
from tele_rest.models.transaction_partner_telegram_api import TransactionPartnerTelegramApi
from tele_rest.models.transaction_partner_user import TransactionPartnerUser
from tele_rest.models.transfer_business_account_stars_post_request import TransferBusinessAccountStarsPostRequest
from tele_rest.models.transfer_gift_post_request import TransferGiftPostRequest
from tele_rest.models.unban_chat_member_post_request import UnbanChatMemberPostRequest
from tele_rest.models.unique_gift import UniqueGift
from tele_rest.models.unique_gift_backdrop import UniqueGiftBackdrop
from tele_rest.models.unique_gift_backdrop_colors import UniqueGiftBackdropColors
from tele_rest.models.unique_gift_info import UniqueGiftInfo
from tele_rest.models.unique_gift_model import UniqueGiftModel
from tele_rest.models.unique_gift_symbol import UniqueGiftSymbol
from tele_rest.models.unpin_chat_message_post_request import UnpinChatMessagePostRequest
from tele_rest.models.update import Update
from tele_rest.models.upgrade_gift_post_request import UpgradeGiftPostRequest
from tele_rest.models.user import User
from tele_rest.models.user_chat_boosts import UserChatBoosts
from tele_rest.models.user_profile_photos import UserProfilePhotos
from tele_rest.models.users_shared import UsersShared
from tele_rest.models.venue import Venue
from tele_rest.models.verify_chat_post_request import VerifyChatPostRequest
from tele_rest.models.verify_user_post_request import VerifyUserPostRequest
from tele_rest.models.video import Video
from tele_rest.models.video_chat_ended import VideoChatEnded
from tele_rest.models.video_chat_participants_invited import VideoChatParticipantsInvited
from tele_rest.models.video_chat_scheduled import VideoChatScheduled
from tele_rest.models.video_note import VideoNote
from tele_rest.models.voice import Voice
from tele_rest.models.web_app_data import WebAppData
from tele_rest.models.web_app_info import WebAppInfo
from tele_rest.models.webhook_info import WebhookInfo
from tele_rest.models.write_access_allowed import WriteAccessAllowed
