# coding: utf-8

# flake8: noqa
"""
Telegram Bot API - REST API Client
The Bot API is an HTTP-based interface created for developers keen on building bots for Telegram. To learn how to create and set up a bot, please consult our Introduction to Bots and Bot FAQ.

## Metadata

- **Copyright**: Copyright (c) 2025 Qntx
- **Author**: ΣX <gitctrlx@gmail.com>
- **Version**: 9.0.0
- **Modified**: 2025-07-02T07:03:17.088738557Z[Etc/UTC]
- **Generator Version**: 7.14.0

<details>
<summary><strong>⚠️ Important Disclaimer & Limitation of Liability</strong></summary>
<br>
> **IMPORTANT**: This software is provided "as is" without any warranties, express or implied, including but not limited
> to warranties of merchantability, fitness for a particular purpose, or non-infringement. The developers, contributors,
> and licensors (collectively, "Developers") make no representations regarding the accuracy, completeness, or reliability
> of this software or its outputs.
>
> This client is not intended to provide financial, investment, tax, or legal advice. It facilitates interaction with the
> Telegram Bot API service but does not endorse or recommend any financial actions, including the purchase, sale, or holding of
> financial instruments (e.g., stocks, bonds, derivatives, cryptocurrencies). Users must consult qualified financial or
> legal professionals before making decisions based on this software's outputs.
>
> Financial markets are inherently speculative and carry significant risks. Using this software in trading, analysis, or
> other financial activities may result in substantial losses, including total loss of capital. The Developers are not
> liable for any losses or damages arising from such use. Users assume full responsibility for validating the software's
> outputs and ensuring their suitability for intended purposes.
>
> This client may rely on third-party data or services (e.g., market feeds, APIs). The Developers do not control or verify
> the accuracy of these services and are not liable for any errors, delays, or losses resulting from their use. Users must
> comply with third-party terms and conditions.
>
> Users are solely responsible for ensuring compliance with all applicable financial, tax, and regulatory requirements in
> their jurisdiction. This includes obtaining necessary licenses or approvals for trading or investment activities. The
> Developers disclaim liability for any legal consequences arising from non-compliance.
>
> To the fullest extent permitted by law, the Developers shall not be liable for any direct, indirect, incidental,
> consequential, or punitive damages arising from the use or inability to use this software, including but not limited to
> loss of profits, data, or business opportunities.

</details>
"""  # noqa: E501


# import models into model package
from tele_rest.models.accepted_gift_types import AcceptedGiftTypes
from tele_rest.models.affiliate_info import AffiliateInfo
from tele_rest.models.animation import Animation
from tele_rest.models.audio import Audio
from tele_rest.models.background_fill import BackgroundFill
from tele_rest.models.background_fill_freeform_gradient import BackgroundFillFreeformGradient
from tele_rest.models.background_fill_gradient import BackgroundFillGradient
from tele_rest.models.background_fill_solid import BackgroundFillSolid
from tele_rest.models.background_type import BackgroundType
from tele_rest.models.background_type_chat_theme import BackgroundTypeChatTheme
from tele_rest.models.background_type_fill import BackgroundTypeFill
from tele_rest.models.background_type_pattern import BackgroundTypePattern
from tele_rest.models.background_type_wallpaper import BackgroundTypeWallpaper
from tele_rest.models.birthdate import Birthdate
from tele_rest.models.bot_command import BotCommand
from tele_rest.models.bot_command_scope import BotCommandScope
from tele_rest.models.bot_command_scope_all_chat_administrators import BotCommandScopeAllChatAdministrators
from tele_rest.models.bot_command_scope_all_group_chats import BotCommandScopeAllGroupChats
from tele_rest.models.bot_command_scope_all_private_chats import BotCommandScopeAllPrivateChats
from tele_rest.models.bot_command_scope_chat import BotCommandScopeChat
from tele_rest.models.bot_command_scope_chat_administrators import BotCommandScopeChatAdministrators
from tele_rest.models.bot_command_scope_chat_member import BotCommandScopeChatMember
from tele_rest.models.bot_command_scope_default import BotCommandScopeDefault
from tele_rest.models.bot_description import BotDescription
from tele_rest.models.bot_name import BotName
from tele_rest.models.bot_short_description import BotShortDescription
from tele_rest.models.business_bot_rights import BusinessBotRights
from tele_rest.models.business_connection import BusinessConnection
from tele_rest.models.business_intro import BusinessIntro
from tele_rest.models.business_location import BusinessLocation
from tele_rest.models.business_messages_deleted import BusinessMessagesDeleted
from tele_rest.models.business_opening_hours import BusinessOpeningHours
from tele_rest.models.business_opening_hours_interval import BusinessOpeningHoursInterval
from tele_rest.models.callback_query import CallbackQuery
from tele_rest.models.chat import Chat
from tele_rest.models.chat_administrator_rights import ChatAdministratorRights
from tele_rest.models.chat_background import ChatBackground
from tele_rest.models.chat_boost import ChatBoost
from tele_rest.models.chat_boost_added import ChatBoostAdded
from tele_rest.models.chat_boost_removed import ChatBoostRemoved
from tele_rest.models.chat_boost_source import ChatBoostSource
from tele_rest.models.chat_boost_source_gift_code import ChatBoostSourceGiftCode
from tele_rest.models.chat_boost_source_giveaway import ChatBoostSourceGiveaway
from tele_rest.models.chat_boost_source_premium import ChatBoostSourcePremium
from tele_rest.models.chat_boost_updated import ChatBoostUpdated
from tele_rest.models.chat_full_info import ChatFullInfo
from tele_rest.models.chat_invite_link import ChatInviteLink
from tele_rest.models.chat_join_request import ChatJoinRequest
from tele_rest.models.chat_location import ChatLocation
from tele_rest.models.chat_member import ChatMember
from tele_rest.models.chat_member_administrator import ChatMemberAdministrator
from tele_rest.models.chat_member_banned import ChatMemberBanned
from tele_rest.models.chat_member_left import ChatMemberLeft
from tele_rest.models.chat_member_member import ChatMemberMember
from tele_rest.models.chat_member_owner import ChatMemberOwner
from tele_rest.models.chat_member_restricted import ChatMemberRestricted
from tele_rest.models.chat_member_updated import ChatMemberUpdated
from tele_rest.models.chat_permissions import ChatPermissions
from tele_rest.models.chat_photo import ChatPhoto
from tele_rest.models.chat_shared import ChatShared
from tele_rest.models.chosen_inline_result import ChosenInlineResult
from tele_rest.models.contact import Contact
from tele_rest.models.copy_text_button import CopyTextButton
from tele_rest.models.dice import Dice
from tele_rest.models.document import Document
from tele_rest.models.encrypted_credentials import EncryptedCredentials
from tele_rest.models.encrypted_passport_element import EncryptedPassportElement
from tele_rest.models.error import Error
from tele_rest.models.external_reply_info import ExternalReplyInfo
from tele_rest.models.file import File
from tele_rest.models.force_reply import ForceReply
from tele_rest.models.forum_topic import ForumTopic
from tele_rest.models.forum_topic_created import ForumTopicCreated
from tele_rest.models.forum_topic_edited import ForumTopicEdited
from tele_rest.models.game import Game
from tele_rest.models.game_high_score import GameHighScore
from tele_rest.models.gift import Gift
from tele_rest.models.gift_info import GiftInfo
from tele_rest.models.gifts import Gifts
from tele_rest.models.giveaway import Giveaway
from tele_rest.models.giveaway_completed import GiveawayCompleted
from tele_rest.models.giveaway_created import GiveawayCreated
from tele_rest.models.giveaway_winners import GiveawayWinners
from tele_rest.models.inaccessible_message import InaccessibleMessage
from tele_rest.models.inline_keyboard_button import InlineKeyboardButton
from tele_rest.models.inline_keyboard_markup import InlineKeyboardMarkup
from tele_rest.models.inline_query import InlineQuery
from tele_rest.models.inline_query_result import InlineQueryResult
from tele_rest.models.inline_query_result_article import InlineQueryResultArticle
from tele_rest.models.inline_query_result_audio import InlineQueryResultAudio
from tele_rest.models.inline_query_result_cached_audio import InlineQueryResultCachedAudio
from tele_rest.models.inline_query_result_cached_document import InlineQueryResultCachedDocument
from tele_rest.models.inline_query_result_cached_gif import InlineQueryResultCachedGif
from tele_rest.models.inline_query_result_cached_mpeg4_gif import InlineQueryResultCachedMpeg4Gif
from tele_rest.models.inline_query_result_cached_photo import InlineQueryResultCachedPhoto
from tele_rest.models.inline_query_result_cached_sticker import InlineQueryResultCachedSticker
from tele_rest.models.inline_query_result_cached_video import InlineQueryResultCachedVideo
from tele_rest.models.inline_query_result_cached_voice import InlineQueryResultCachedVoice
from tele_rest.models.inline_query_result_contact import InlineQueryResultContact
from tele_rest.models.inline_query_result_document import InlineQueryResultDocument
from tele_rest.models.inline_query_result_game import InlineQueryResultGame
from tele_rest.models.inline_query_result_gif import InlineQueryResultGif
from tele_rest.models.inline_query_result_location import InlineQueryResultLocation
from tele_rest.models.inline_query_result_mpeg4_gif import InlineQueryResultMpeg4Gif
from tele_rest.models.inline_query_result_photo import InlineQueryResultPhoto
from tele_rest.models.inline_query_result_venue import InlineQueryResultVenue
from tele_rest.models.inline_query_result_video import InlineQueryResultVideo
from tele_rest.models.inline_query_result_voice import InlineQueryResultVoice
from tele_rest.models.inline_query_results_button import InlineQueryResultsButton
from tele_rest.models.input_contact_message_content import InputContactMessageContent
from tele_rest.models.input_invoice_message_content import InputInvoiceMessageContent
from tele_rest.models.input_location_message_content import InputLocationMessageContent
from tele_rest.models.input_media import InputMedia
from tele_rest.models.input_media_animation import InputMediaAnimation
from tele_rest.models.input_media_audio import InputMediaAudio
from tele_rest.models.input_media_document import InputMediaDocument
from tele_rest.models.input_media_photo import InputMediaPhoto
from tele_rest.models.input_media_video import InputMediaVideo
from tele_rest.models.input_message_content import InputMessageContent
from tele_rest.models.input_paid_media import InputPaidMedia
from tele_rest.models.input_paid_media_photo import InputPaidMediaPhoto
from tele_rest.models.input_paid_media_video import InputPaidMediaVideo
from tele_rest.models.input_poll_option import InputPollOption
from tele_rest.models.input_profile_photo import InputProfilePhoto
from tele_rest.models.input_profile_photo_animated import InputProfilePhotoAnimated
from tele_rest.models.input_profile_photo_static import InputProfilePhotoStatic
from tele_rest.models.input_sticker import InputSticker
from tele_rest.models.input_story_content import InputStoryContent
from tele_rest.models.input_story_content_photo import InputStoryContentPhoto
from tele_rest.models.input_story_content_video import InputStoryContentVideo
from tele_rest.models.input_text_message_content import InputTextMessageContent
from tele_rest.models.input_venue_message_content import InputVenueMessageContent
from tele_rest.models.invoice import Invoice
from tele_rest.models.keyboard_button import KeyboardButton
from tele_rest.models.keyboard_button_poll_type import KeyboardButtonPollType
from tele_rest.models.keyboard_button_request_chat import KeyboardButtonRequestChat
from tele_rest.models.keyboard_button_request_users import KeyboardButtonRequestUsers
from tele_rest.models.labeled_price import LabeledPrice
from tele_rest.models.link_preview_options import LinkPreviewOptions
from tele_rest.models.location import Location
from tele_rest.models.location_address import LocationAddress
from tele_rest.models.login_url import LoginUrl
from tele_rest.models.mask_position import MaskPosition
from tele_rest.models.maybe_inaccessible_message import MaybeInaccessibleMessage
from tele_rest.models.menu_button import MenuButton
from tele_rest.models.menu_button_commands import MenuButtonCommands
from tele_rest.models.menu_button_default import MenuButtonDefault
from tele_rest.models.menu_button_web_app import MenuButtonWebApp
from tele_rest.models.message import Message
from tele_rest.models.message_auto_delete_timer_changed import MessageAutoDeleteTimerChanged
from tele_rest.models.message_entity import MessageEntity
from tele_rest.models.message_id import MessageId
from tele_rest.models.message_origin import MessageOrigin
from tele_rest.models.message_origin_channel import MessageOriginChannel
from tele_rest.models.message_origin_chat import MessageOriginChat
from tele_rest.models.message_origin_hidden_user import MessageOriginHiddenUser
from tele_rest.models.message_origin_user import MessageOriginUser
from tele_rest.models.message_reaction_count_updated import MessageReactionCountUpdated
from tele_rest.models.message_reaction_updated import MessageReactionUpdated
from tele_rest.models.order_info import OrderInfo
from tele_rest.models.owned_gift import OwnedGift
from tele_rest.models.owned_gift_regular import OwnedGiftRegular
from tele_rest.models.owned_gift_unique import OwnedGiftUnique
from tele_rest.models.owned_gifts import OwnedGifts
from tele_rest.models.paid_media import PaidMedia
from tele_rest.models.paid_media_info import PaidMediaInfo
from tele_rest.models.paid_media_photo import PaidMediaPhoto
from tele_rest.models.paid_media_preview import PaidMediaPreview
from tele_rest.models.paid_media_purchased import PaidMediaPurchased
from tele_rest.models.paid_media_video import PaidMediaVideo
from tele_rest.models.paid_message_price_changed import PaidMessagePriceChanged
from tele_rest.models.passport_data import PassportData
from tele_rest.models.passport_element_error import PassportElementError
from tele_rest.models.passport_element_error_data_field import PassportElementErrorDataField
from tele_rest.models.passport_element_error_file import PassportElementErrorFile
from tele_rest.models.passport_element_error_files import PassportElementErrorFiles
from tele_rest.models.passport_element_error_front_side import PassportElementErrorFrontSide
from tele_rest.models.passport_element_error_reverse_side import PassportElementErrorReverseSide
from tele_rest.models.passport_element_error_selfie import PassportElementErrorSelfie
from tele_rest.models.passport_element_error_translation_file import PassportElementErrorTranslationFile
from tele_rest.models.passport_element_error_translation_files import PassportElementErrorTranslationFiles
from tele_rest.models.passport_element_error_unspecified import PassportElementErrorUnspecified
from tele_rest.models.passport_file import PassportFile
from tele_rest.models.photo_size import PhotoSize
from tele_rest.models.poll import Poll
from tele_rest.models.poll_answer import PollAnswer
from tele_rest.models.poll_option import PollOption
from tele_rest.models.post_answer_callback_query_request import PostAnswerCallbackQueryRequest
from tele_rest.models.post_answer_inline_query_request import PostAnswerInlineQueryRequest
from tele_rest.models.post_answer_pre_checkout_query_request import PostAnswerPreCheckoutQueryRequest
from tele_rest.models.post_answer_shipping_query_request import PostAnswerShippingQueryRequest
from tele_rest.models.post_answer_web_app_query200_response import PostAnswerWebAppQuery200Response
from tele_rest.models.post_answer_web_app_query_request import PostAnswerWebAppQueryRequest
from tele_rest.models.post_approve_chat_join_request_request import PostApproveChatJoinRequestRequest
from tele_rest.models.post_ban_chat_member_request import PostBanChatMemberRequest
from tele_rest.models.post_ban_chat_member_request_chat_id import PostBanChatMemberRequestChatId
from tele_rest.models.post_ban_chat_sender_chat_request import PostBanChatSenderChatRequest
from tele_rest.models.post_close_forum_topic_request import PostCloseForumTopicRequest
from tele_rest.models.post_convert_gift_to_stars_request import PostConvertGiftToStarsRequest
from tele_rest.models.post_copy_message200_response import PostCopyMessage200Response
from tele_rest.models.post_copy_message_request import PostCopyMessageRequest
from tele_rest.models.post_copy_messages_request import PostCopyMessagesRequest
from tele_rest.models.post_create_chat_invite_link200_response import PostCreateChatInviteLink200Response
from tele_rest.models.post_create_chat_invite_link_request import PostCreateChatInviteLinkRequest
from tele_rest.models.post_create_chat_subscription_invite_link_request import PostCreateChatSubscriptionInviteLinkRequest
from tele_rest.models.post_create_chat_subscription_invite_link_request_chat_id import PostCreateChatSubscriptionInviteLinkRequestChatId
from tele_rest.models.post_create_forum_topic200_response import PostCreateForumTopic200Response
from tele_rest.models.post_create_forum_topic_request import PostCreateForumTopicRequest
from tele_rest.models.post_create_invoice_link_request import PostCreateInvoiceLinkRequest
from tele_rest.models.post_delete_business_messages_request import PostDeleteBusinessMessagesRequest
from tele_rest.models.post_delete_chat_sticker_set_request import PostDeleteChatStickerSetRequest
from tele_rest.models.post_delete_message_request import PostDeleteMessageRequest
from tele_rest.models.post_delete_messages_request import PostDeleteMessagesRequest
from tele_rest.models.post_delete_my_commands_request import PostDeleteMyCommandsRequest
from tele_rest.models.post_delete_sticker_from_set_request import PostDeleteStickerFromSetRequest
from tele_rest.models.post_delete_sticker_set_request import PostDeleteStickerSetRequest
from tele_rest.models.post_delete_story_request import PostDeleteStoryRequest
from tele_rest.models.post_delete_webhook_request import PostDeleteWebhookRequest
from tele_rest.models.post_edit_chat_invite_link_request import PostEditChatInviteLinkRequest
from tele_rest.models.post_edit_chat_subscription_invite_link_request import PostEditChatSubscriptionInviteLinkRequest
from tele_rest.models.post_edit_forum_topic_request import PostEditForumTopicRequest
from tele_rest.models.post_edit_general_forum_topic_request import PostEditGeneralForumTopicRequest
from tele_rest.models.post_edit_message_caption_request import PostEditMessageCaptionRequest
from tele_rest.models.post_edit_message_live_location_request import PostEditMessageLiveLocationRequest
from tele_rest.models.post_edit_message_reply_markup_request import PostEditMessageReplyMarkupRequest
from tele_rest.models.post_edit_message_text200_response import PostEditMessageText200Response
from tele_rest.models.post_edit_message_text200_response_result import PostEditMessageText200ResponseResult
from tele_rest.models.post_edit_message_text_request import PostEditMessageTextRequest
from tele_rest.models.post_edit_message_text_request_chat_id import PostEditMessageTextRequestChatId
from tele_rest.models.post_edit_user_star_subscription_request import PostEditUserStarSubscriptionRequest
from tele_rest.models.post_export_chat_invite_link200_response import PostExportChatInviteLink200Response
from tele_rest.models.post_export_chat_invite_link_request import PostExportChatInviteLinkRequest
from tele_rest.models.post_forward_message_request import PostForwardMessageRequest
from tele_rest.models.post_forward_message_request_from_chat_id import PostForwardMessageRequestFromChatId
from tele_rest.models.post_forward_messages200_response import PostForwardMessages200Response
from tele_rest.models.post_forward_messages_request import PostForwardMessagesRequest
from tele_rest.models.post_forward_messages_request_from_chat_id import PostForwardMessagesRequestFromChatId
from tele_rest.models.post_get_available_gifts200_response import PostGetAvailableGifts200Response
from tele_rest.models.post_get_business_account_gifts200_response import PostGetBusinessAccountGifts200Response
from tele_rest.models.post_get_business_account_gifts_request import PostGetBusinessAccountGiftsRequest
from tele_rest.models.post_get_business_account_star_balance200_response import PostGetBusinessAccountStarBalance200Response
from tele_rest.models.post_get_business_connection200_response import PostGetBusinessConnection200Response
from tele_rest.models.post_get_business_connection_request import PostGetBusinessConnectionRequest
from tele_rest.models.post_get_chat200_response import PostGetChat200Response
from tele_rest.models.post_get_chat_administrators200_response import PostGetChatAdministrators200Response
from tele_rest.models.post_get_chat_member200_response import PostGetChatMember200Response
from tele_rest.models.post_get_chat_member_count200_response import PostGetChatMemberCount200Response
from tele_rest.models.post_get_chat_member_request import PostGetChatMemberRequest
from tele_rest.models.post_get_chat_menu_button200_response import PostGetChatMenuButton200Response
from tele_rest.models.post_get_chat_menu_button_request import PostGetChatMenuButtonRequest
from tele_rest.models.post_get_custom_emoji_stickers_request import PostGetCustomEmojiStickersRequest
from tele_rest.models.post_get_file200_response import PostGetFile200Response
from tele_rest.models.post_get_file_request import PostGetFileRequest
from tele_rest.models.post_get_forum_topic_icon_stickers200_response import PostGetForumTopicIconStickers200Response
from tele_rest.models.post_get_game_high_scores200_response import PostGetGameHighScores200Response
from tele_rest.models.post_get_game_high_scores_request import PostGetGameHighScoresRequest
from tele_rest.models.post_get_me200_response import PostGetMe200Response
from tele_rest.models.post_get_my_commands200_response import PostGetMyCommands200Response
from tele_rest.models.post_get_my_commands_request import PostGetMyCommandsRequest
from tele_rest.models.post_get_my_default_administrator_rights200_response import PostGetMyDefaultAdministratorRights200Response
from tele_rest.models.post_get_my_default_administrator_rights_request import PostGetMyDefaultAdministratorRightsRequest
from tele_rest.models.post_get_my_description200_response import PostGetMyDescription200Response
from tele_rest.models.post_get_my_name200_response import PostGetMyName200Response
from tele_rest.models.post_get_my_name_request import PostGetMyNameRequest
from tele_rest.models.post_get_my_short_description200_response import PostGetMyShortDescription200Response
from tele_rest.models.post_get_star_transactions200_response import PostGetStarTransactions200Response
from tele_rest.models.post_get_star_transactions_request import PostGetStarTransactionsRequest
from tele_rest.models.post_get_sticker_set200_response import PostGetStickerSet200Response
from tele_rest.models.post_get_sticker_set_request import PostGetStickerSetRequest
from tele_rest.models.post_get_updates200_response import PostGetUpdates200Response
from tele_rest.models.post_get_updates_request import PostGetUpdatesRequest
from tele_rest.models.post_get_user_chat_boosts200_response import PostGetUserChatBoosts200Response
from tele_rest.models.post_get_user_chat_boosts_request import PostGetUserChatBoostsRequest
from tele_rest.models.post_get_user_chat_boosts_request_chat_id import PostGetUserChatBoostsRequestChatId
from tele_rest.models.post_get_user_profile_photos200_response import PostGetUserProfilePhotos200Response
from tele_rest.models.post_get_user_profile_photos_request import PostGetUserProfilePhotosRequest
from tele_rest.models.post_get_webhook_info200_response import PostGetWebhookInfo200Response
from tele_rest.models.post_gift_premium_subscription_request import PostGiftPremiumSubscriptionRequest
from tele_rest.models.post_leave_chat_request import PostLeaveChatRequest
from tele_rest.models.post_leave_chat_request_chat_id import PostLeaveChatRequestChatId
from tele_rest.models.post_pin_chat_message_request import PostPinChatMessageRequest
from tele_rest.models.post_post_story200_response import PostPostStory200Response
from tele_rest.models.post_promote_chat_member_request import PostPromoteChatMemberRequest
from tele_rest.models.post_read_business_message_request import PostReadBusinessMessageRequest
from tele_rest.models.post_refund_star_payment_request import PostRefundStarPaymentRequest
from tele_rest.models.post_remove_business_account_profile_photo_request import PostRemoveBusinessAccountProfilePhotoRequest
from tele_rest.models.post_remove_user_verification_request import PostRemoveUserVerificationRequest
from tele_rest.models.post_restrict_chat_member_request import PostRestrictChatMemberRequest
from tele_rest.models.post_restrict_chat_member_request_chat_id import PostRestrictChatMemberRequestChatId
from tele_rest.models.post_revoke_chat_invite_link_request import PostRevokeChatInviteLinkRequest
from tele_rest.models.post_revoke_chat_invite_link_request_chat_id import PostRevokeChatInviteLinkRequestChatId
from tele_rest.models.post_save_prepared_inline_message200_response import PostSavePreparedInlineMessage200Response
from tele_rest.models.post_save_prepared_inline_message_request import PostSavePreparedInlineMessageRequest
from tele_rest.models.post_send_animation_request_animation import PostSendAnimationRequestAnimation
from tele_rest.models.post_send_audio_request_audio import PostSendAudioRequestAudio
from tele_rest.models.post_send_audio_request_thumbnail import PostSendAudioRequestThumbnail
from tele_rest.models.post_send_chat_action_request import PostSendChatActionRequest
from tele_rest.models.post_send_contact_request import PostSendContactRequest
from tele_rest.models.post_send_dice_request import PostSendDiceRequest
from tele_rest.models.post_send_document_request_document import PostSendDocumentRequestDocument
from tele_rest.models.post_send_game_request import PostSendGameRequest
from tele_rest.models.post_send_gift_request import PostSendGiftRequest
from tele_rest.models.post_send_gift_request_chat_id import PostSendGiftRequestChatId
from tele_rest.models.post_send_invoice_request import PostSendInvoiceRequest
from tele_rest.models.post_send_location_request import PostSendLocationRequest
from tele_rest.models.post_send_media_group200_response import PostSendMediaGroup200Response
from tele_rest.models.post_send_media_group_request_media_inner import PostSendMediaGroupRequestMediaInner
from tele_rest.models.post_send_message200_response import PostSendMessage200Response
from tele_rest.models.post_send_message_request import PostSendMessageRequest
from tele_rest.models.post_send_message_request_chat_id import PostSendMessageRequestChatId
from tele_rest.models.post_send_message_request_reply_markup import PostSendMessageRequestReplyMarkup
from tele_rest.models.post_send_paid_media_request_chat_id import PostSendPaidMediaRequestChatId
from tele_rest.models.post_send_photo_request_photo import PostSendPhotoRequestPhoto
from tele_rest.models.post_send_poll_request import PostSendPollRequest
from tele_rest.models.post_send_sticker_request_sticker import PostSendStickerRequestSticker
from tele_rest.models.post_send_venue_request import PostSendVenueRequest
from tele_rest.models.post_send_video_note_request_video_note import PostSendVideoNoteRequestVideoNote
from tele_rest.models.post_send_video_request_cover import PostSendVideoRequestCover
from tele_rest.models.post_send_video_request_video import PostSendVideoRequestVideo
from tele_rest.models.post_send_voice_request_voice import PostSendVoiceRequestVoice
from tele_rest.models.post_set_business_account_bio_request import PostSetBusinessAccountBioRequest
from tele_rest.models.post_set_business_account_gift_settings_request import PostSetBusinessAccountGiftSettingsRequest
from tele_rest.models.post_set_business_account_name_request import PostSetBusinessAccountNameRequest
from tele_rest.models.post_set_business_account_username_request import PostSetBusinessAccountUsernameRequest
from tele_rest.models.post_set_chat_administrator_custom_title_request import PostSetChatAdministratorCustomTitleRequest
from tele_rest.models.post_set_chat_description_request import PostSetChatDescriptionRequest
from tele_rest.models.post_set_chat_menu_button_request import PostSetChatMenuButtonRequest
from tele_rest.models.post_set_chat_permissions_request import PostSetChatPermissionsRequest
from tele_rest.models.post_set_chat_sticker_set_request import PostSetChatStickerSetRequest
from tele_rest.models.post_set_chat_title_request import PostSetChatTitleRequest
from tele_rest.models.post_set_custom_emoji_sticker_set_thumbnail_request import PostSetCustomEmojiStickerSetThumbnailRequest
from tele_rest.models.post_set_game_score_request import PostSetGameScoreRequest
from tele_rest.models.post_set_message_reaction_request import PostSetMessageReactionRequest
from tele_rest.models.post_set_my_commands_request import PostSetMyCommandsRequest
from tele_rest.models.post_set_my_default_administrator_rights_request import PostSetMyDefaultAdministratorRightsRequest
from tele_rest.models.post_set_my_description_request import PostSetMyDescriptionRequest
from tele_rest.models.post_set_my_name_request import PostSetMyNameRequest
from tele_rest.models.post_set_my_short_description_request import PostSetMyShortDescriptionRequest
from tele_rest.models.post_set_passport_data_errors_request import PostSetPassportDataErrorsRequest
from tele_rest.models.post_set_sticker_emoji_list_request import PostSetStickerEmojiListRequest
from tele_rest.models.post_set_sticker_keywords_request import PostSetStickerKeywordsRequest
from tele_rest.models.post_set_sticker_mask_position_request import PostSetStickerMaskPositionRequest
from tele_rest.models.post_set_sticker_position_in_set_request import PostSetStickerPositionInSetRequest
from tele_rest.models.post_set_sticker_set_thumbnail_request_thumbnail import PostSetStickerSetThumbnailRequestThumbnail
from tele_rest.models.post_set_sticker_set_title_request import PostSetStickerSetTitleRequest
from tele_rest.models.post_set_user_emoji_status_request import PostSetUserEmojiStatusRequest
from tele_rest.models.post_set_webhook200_response import PostSetWebhook200Response
from tele_rest.models.post_stop_message_live_location_request import PostStopMessageLiveLocationRequest
from tele_rest.models.post_stop_poll200_response import PostStopPoll200Response
from tele_rest.models.post_stop_poll_request import PostStopPollRequest
from tele_rest.models.post_transfer_business_account_stars_request import PostTransferBusinessAccountStarsRequest
from tele_rest.models.post_transfer_gift_request import PostTransferGiftRequest
from tele_rest.models.post_unban_chat_member_request import PostUnbanChatMemberRequest
from tele_rest.models.post_unpin_chat_message_request import PostUnpinChatMessageRequest
from tele_rest.models.post_upgrade_gift_request import PostUpgradeGiftRequest
from tele_rest.models.post_verify_chat_request import PostVerifyChatRequest
from tele_rest.models.post_verify_user_request import PostVerifyUserRequest
from tele_rest.models.pre_checkout_query import PreCheckoutQuery
from tele_rest.models.prepared_inline_message import PreparedInlineMessage
from tele_rest.models.proximity_alert_triggered import ProximityAlertTriggered
from tele_rest.models.reaction_count import ReactionCount
from tele_rest.models.reaction_type import ReactionType
from tele_rest.models.reaction_type_custom_emoji import ReactionTypeCustomEmoji
from tele_rest.models.reaction_type_emoji import ReactionTypeEmoji
from tele_rest.models.reaction_type_paid import ReactionTypePaid
from tele_rest.models.refunded_payment import RefundedPayment
from tele_rest.models.reply_keyboard_markup import ReplyKeyboardMarkup
from tele_rest.models.reply_keyboard_remove import ReplyKeyboardRemove
from tele_rest.models.reply_parameters import ReplyParameters
from tele_rest.models.reply_parameters_chat_id import ReplyParametersChatId
from tele_rest.models.response_parameters import ResponseParameters
from tele_rest.models.revenue_withdrawal_state import RevenueWithdrawalState
from tele_rest.models.revenue_withdrawal_state_failed import RevenueWithdrawalStateFailed
from tele_rest.models.revenue_withdrawal_state_pending import RevenueWithdrawalStatePending
from tele_rest.models.revenue_withdrawal_state_succeeded import RevenueWithdrawalStateSucceeded
from tele_rest.models.sent_web_app_message import SentWebAppMessage
from tele_rest.models.shared_user import SharedUser
from tele_rest.models.shipping_address import ShippingAddress
from tele_rest.models.shipping_option import ShippingOption
from tele_rest.models.shipping_query import ShippingQuery
from tele_rest.models.star_amount import StarAmount
from tele_rest.models.star_transaction import StarTransaction
from tele_rest.models.star_transactions import StarTransactions
from tele_rest.models.sticker import Sticker
from tele_rest.models.sticker_set import StickerSet
from tele_rest.models.story import Story
from tele_rest.models.story_area import StoryArea
from tele_rest.models.story_area_position import StoryAreaPosition
from tele_rest.models.story_area_type import StoryAreaType
from tele_rest.models.story_area_type_link import StoryAreaTypeLink
from tele_rest.models.story_area_type_location import StoryAreaTypeLocation
from tele_rest.models.story_area_type_suggested_reaction import StoryAreaTypeSuggestedReaction
from tele_rest.models.story_area_type_unique_gift import StoryAreaTypeUniqueGift
from tele_rest.models.story_area_type_weather import StoryAreaTypeWeather
from tele_rest.models.successful_payment import SuccessfulPayment
from tele_rest.models.switch_inline_query_chosen_chat import SwitchInlineQueryChosenChat
from tele_rest.models.text_quote import TextQuote
from tele_rest.models.transaction_partner import TransactionPartner
from tele_rest.models.transaction_partner_affiliate_program import TransactionPartnerAffiliateProgram
from tele_rest.models.transaction_partner_chat import TransactionPartnerChat
from tele_rest.models.transaction_partner_fragment import TransactionPartnerFragment
from tele_rest.models.transaction_partner_other import TransactionPartnerOther
from tele_rest.models.transaction_partner_telegram_ads import TransactionPartnerTelegramAds
from tele_rest.models.transaction_partner_telegram_api import TransactionPartnerTelegramApi
from tele_rest.models.transaction_partner_user import TransactionPartnerUser
from tele_rest.models.unique_gift import UniqueGift
from tele_rest.models.unique_gift_backdrop import UniqueGiftBackdrop
from tele_rest.models.unique_gift_backdrop_colors import UniqueGiftBackdropColors
from tele_rest.models.unique_gift_info import UniqueGiftInfo
from tele_rest.models.unique_gift_model import UniqueGiftModel
from tele_rest.models.unique_gift_symbol import UniqueGiftSymbol
from tele_rest.models.update import Update
from tele_rest.models.user import User
from tele_rest.models.user_chat_boosts import UserChatBoosts
from tele_rest.models.user_profile_photos import UserProfilePhotos
from tele_rest.models.users_shared import UsersShared
from tele_rest.models.venue import Venue
from tele_rest.models.video import Video
from tele_rest.models.video_chat_ended import VideoChatEnded
from tele_rest.models.video_chat_participants_invited import VideoChatParticipantsInvited
from tele_rest.models.video_chat_scheduled import VideoChatScheduled
from tele_rest.models.video_note import VideoNote
from tele_rest.models.voice import Voice
from tele_rest.models.web_app_data import WebAppData
from tele_rest.models.web_app_info import WebAppInfo
from tele_rest.models.webhook_info import WebhookInfo
from tele_rest.models.write_access_allowed import WriteAccessAllowed
